channels:
  - defaults
dependencies:
  # common
  - cuda=12.4
  - pip

  - pip:
    - jupyterlab
    - jupyterlab_execute_time
    - jupyterlab-vim
    - ipywidgets

    # summarization
    - huggginface_hub

    # transcription
    - matplotlib
    - openai-whisper
    - pandas
    - pydub
    - pytubefix
    - tabulate
    - openai-whisper
